app_id: "8dafc151-8473-44a9-861f-af301c71c38b"
app_secret: "gpGF0;bhjqzIYCNH2852~-~"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
